name: pathmc
channels:
  - conda-forge
dependencies:
  - python=3.12
  - arviz<1
  - graphviz
  - jupyter
  - numpy<2.4
  - pandas
  - patsy
  - pymc
  - nutpie
  - pymc-marketing
  - pyyaml
  - pip
  - pip:
      - -e ".[dev]"
